# Generated by Django 4.2.8 on 2023-12-31 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('status', models.IntegerField()),
                ('origin_lat', models.IntegerField()),
                ('origin_lon', models.IntegerField()),
                ('dest_lat', models.IntegerField()),
                ('dest_lon', models.IntegerField()),
                ('price', models.IntegerField()),
                ('delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_delivery_man', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
